### PR TITLE
Added concat functionality

### PR DESCRIPTION
**Pull request by bmcgary**

### CODE REVIEW

**Review by jasonsjones — APPROVED** [review]
Awesome PR!  Thanks for taking the time to update the documentation and add the test.  It makes the review super easy 💯 👍

**Comment by bmcgary** [comment]
Hey @jasonsjones can you update this lib on npm?

**Comment by jasonsjones** [comment]
Oh yes...definitely.  I'll try to get it done later today.  Thanks for the follow up! :wink:

**Comment by jasonsjones** [comment]
Done. ✅

**Comment by bmcgary** [comment]
Thanks!

**Pull request merged**
